const matrix = {
  lapiseiraP207: [
    [200, 200, 800, 1200, 400, 1200, 1200, 200],
    ...Array.from(Array(4), _ => Array(8).fill(0)),
  ],
  corpoExterno207: Array.from(Array(5), _ => Array(8).fill(0)),
  presilhaDeBolso: Array.from(Array(5), _ => Array(8).fill(0)),
  miolo207: Array.from(Array(5), _ => Array(8).fill(0)),
  corpoDaPonteira: Array.from(Array(5), _ => Array(8).fill(0)),
  guiaDaPonteira: Array.from(Array(5), _ => Array(8).fill(0)),
  tampa: Array.from(Array(5), _ => Array(8).fill(0)),
  plasticoABS: Array.from(Array(5), _ => Array(8).fill(0)),
  coranteAzul: Array.from(Array(5), _ => Array(8).fill(0)),
  tira1mm: Array.from(Array(5), _ => Array(8).fill(0)),
  borracha: Array.from(Array(5), _ => Array(8).fill(0)),
  capaDaBorracha: Array.from(Array(5), _ => Array(8).fill(0)),
  mioloInterno207: Array.from(Array(5), _ => Array(8).fill(0)),
  grafite7mm: Array.from(Array(5), _ => Array(8).fill(0)),
  fioDeBorracha: Array.from(Array(5), _ => Array(8).fill(0)),
  mola: Array.from(Array(5), _ => Array(8).fill(0)),
  corpoDoMiolo: Array.from(Array(5), _ => Array(8).fill(0)),
  suporteDaGarra: Array.from(Array(5), _ => Array(8).fill(0)),
  capaDaGarra: Array.from(Array(5), _ => Array(8).fill(0)),
  garras: Array.from(Array(5), _ => Array(8).fill(0)),
  corantePreto: Array.from(Array(5), _ => Array(8).fill(0)),
};
