const source = {
  acquired: 'Comprado',
  produced: 'Produzido',
};

const products = {
  lapiseiraP207: {
    name: 'Lapiseira P207',
    source: source.produced,
    minimumLot: 700,
    leadTime: 1,
    safetyStock: 0,
    initialStock: 550,
    matrix: [
      [200, 200, 800, 1200, 400, 1200, 1200, 200],
      ...Array.from(Array(4), _ => Array(8).fill(0)),
    ],
  },
  corpoExterno207: {
    name: 'Corpo externo 207',
    source: source.produced,
    minimumLot: 500,
    leadTime: 2,
    safetyStock: 0,
    initialStock: 0,
    matrix: Array.from(Array(5), _ => Array(8).fill(0)),
  },
  presilhaDeBolso: {
    name: 'Presilha de bolso',
    source: source.acquired,
    minimumLot: 50,
    leadTime: 1,
    safetyStock: 0,
    initialStock: 0,
    matrix: Array.from(Array(5), _ => Array(8).fill(0)),
  },
  miolo207: {
    name: 'Miolo 207',
    source: source.produced,
    minimumLot: 500,
    leadTime: 1,
    safetyStock: 0,
    initialStock: 0,
    matrix: Array.from(Array(5), _ => Array(8).fill(0)),
  },
  corpoDaPonteira: {
    name: 'Corpo da ponteira',
    source: source.acquired,
    minimumLot: 50,
    leadTime: 2,
    safetyStock: 0,
    initialStock: 0,
    matrix: Array.from(Array(5), _ => Array(8).fill(0)),
  },
  guiaDaPonteira: {
    name: 'Guia da ponteira',
    source: source.acquired,
    minimumLot: 50,
    leadTime: 1,
    safetyStock: 0,
    initialStock: 0,
    matrix: Array.from(Array(5), _ => Array(8).fill(0)),
  },
  tampa: {
    name: 'Tampa',
    source: source.produced,
    minimumLot: 500,
    leadTime: 1,
    safetyStock: 0,
    initialStock: 0,
    matrix: Array.from(Array(5), _ => Array(8).fill(0)),
  },
  plasticoABS: {
    name: 'Plástico ABS',
    source: source.acquired,
    minimumLot: 50,
    leadTime: 1,
    safetyStock: 0,
    initialStock: 0,
    matrix: Array.from(Array(5), _ => Array(8).fill(0)),
  },
  coranteAzul: {
    name: 'Corante azul',
    source: source.acquired,
    minimumLot: 50,
    leadTime: 2,
    safetyStock: 0,
    initialStock: 0,
    matrix: Array.from(Array(5), _ => Array(8).fill(0)),
  },
  tira1mm: {
    name: 'Tira 0,1 mm',
    source: source.acquired,
    minimumLot: 50,
    leadTime: 1,
    safetyStock: 0,
    initialStock: 0,
    matrix: Array.from(Array(5), _ => Array(8).fill(0)),
  },
  borracha: {
    name: 'Borracha',
    source: source.produced,
    minimumLot: 1,
    leadTime: 1,
    safetyStock: 0,
    initialStock: 0,
    matrix: Array.from(Array(5), _ => Array(8).fill(0)),
  },
  capaDaBorracha: {
    name: 'Capa da borracha',
    source: source.produced,
    minimumLot: 1,
    leadTime: 1,
    safetyStock: 0,
    initialStock: 0,
    matrix: Array.from(Array(5), _ => Array(8).fill(0)),
  },
  mioloInterno207: {
    name: 'Miolo interno 207',
    source: source.produced,
    minimumLot: 1,
    leadTime: 3,
    safetyStock: 0,
    initialStock: 0,
    matrix: Array.from(Array(5), _ => Array(8).fill(0)),
  },
  grafite7mm: {
    name: 'Grafite 0,7 mm',
    source: source.acquired,
    minimumLot: 50,
    leadTime: 2,
    safetyStock: 0,
    initialStock: 0,
    matrix: Array.from(Array(5), _ => Array(8).fill(0)),
  },
  fioDeBorracha: {
    name: 'Fio de borracha',
    source: source.acquired,
    minimumLot: 50,
    leadTime: 1,
    safetyStock: 0,
    initialStock: 0,
    matrix: Array.from(Array(5), _ => Array(8).fill(0)),
  },
  mola: {
    name: 'Mola',
    source: source.acquired,
    minimumLot: 50,
    leadTime: 1,
    safetyStock: 0,
    initialStock: 0,
    matrix: Array.from(Array(5), _ => Array(8).fill(0)),
  },
  corpoDoMiolo: {
    name: 'Corpo do miolo',
    source: source.produced,
    minimumLot: 1,
    leadTime: 2,
    safetyStock: 0,
    initialStock: 0,
    matrix: Array.from(Array(5), _ => Array(8).fill(0)),
  },
  suporteDaGarra: {
    name: 'Suporte da garra',
    source: source.acquired,
    minimumLot: 50,
    leadTime: 2,
    safetyStock: 0,
    initialStock: 0,
    matrix: Array.from(Array(5), _ => Array(8).fill(0)),
  },
  capaDaGarra: {
    name: 'Capa da garra',
    source: source.acquired,
    minimumLot: 50,
    leadTime: 3,
    safetyStock: 0,
    initialStock: 0,
    matrix: Array.from(Array(5), _ => Array(8).fill(0)),
  },
  garras: {
    name: 'Garras',
    source: source.acquired,
    minimumLot: 50,
    leadTime: 1,
    safetyStock: 0,
    initialStock: 0,
    matrix: Array.from(Array(5), _ => Array(8).fill(0)),
  },
  corantePreto: {
    name: 'Corante preto',
    source: source.acquired,
    minimumLot: 50,
    leadTime: 2,
    safetyStock: 0,
    initialStock: 0,
    matrix: Array.from(Array(5), _ => Array(8).fill(0)),
  },
};
